config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  resources :users, only: [:index, :show]
  as :user do

end
  #devise_for :users, :controllers => { :registrations => "user/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/home', to: 'pages#home'
  get '/sortlike', to: 'contents#sortlike'
  resources :contents do
  	member do
  		post 'like'
  	end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ActiveRecord::Base
	belongs_to :user
	has_many :likes
	validates :user_id, presence: true
	validates :name, presence: true,
					 length: {minimum: 5,maximum: 100}
	validates :summary, presence: true,
					 length: {minimum: 10,maximum: 500}
	validates :description, presence: true,
					 length: {minimum: 50,maximum: 10000}
	mount_uploader :picture, PictureUploader 
	validate :picture_size
    def totallike
    	self.likes.where(like: true).size
    end

	private
		def picture_size
		if picture.size > 5.megabytes
		errors.add(:picture, "should be less than 5MB" )
		end
	    end	
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :content

	validates_uniqueness_of :user,scope: :content

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :contents,:dependent => :destroy
	has_many :likes,:dependent => :destroy
	before_save { self.email = email.downcase }
	mount_uploader :profilepic, ProfilepicUploader
	validates :username, presence: true,
					 length: {minimum: 5,maximum: 100}
	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true,
					 length: {maximum: 105},
					 uniqueness: { case_sensitive: false},
					 format: { with: VALID_EMAIL_REGEX }
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :profilepic])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :profilepic])
  end
  
def after_sign_in_path_for(*)
    contents_path
  end
  def after_sign_up_path_for(*)
    contents_path
  end
   
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
	require 'will_paginate/array'
	def index
		@contents = Content.all.order(updated_at: :desc).paginate(page: params[:page],per_page: 4)
	end
	def sortlike
		if user_signed_in?
		@contents = Content.all.sort_by{|likes| likes.totallike}.reverse.paginate(page: params[:page],per_page: 4)
	    else
		redirect_to contents_path
	    end
	end

	def show
		if user_signed_in?
		@content = Content.find(params[:id])
		else
		redirect_to contents_path
	    end
	end
	def new
		if user_signed_in?
		@content = Content.new
	else
		redirect_to contents_path
		end
	end
	def create
		@content = Content.new(content_params)
		@content.user = current_user

			if @content.save
				redirect_to contents_path
			else
				render :new
			end
			
	end
	def like
		if user_signed_in?
				@content=Content.find(params[:id])
				like=Like.create(like: params[:like],user: current_user, content: @content)
				
		        if like.valid?
				   flash[:success] = "your selection was succesfull"
				   redirect_back fallback_location: content_path(@content)
		 else
				    flash[:danger] = "you can only like or dislike once"
				    redirect_back fallback_location: content_path(@content)
		       end
		       else
		redirect_to new_user_session_path
	    end

	end

	def edit
		if user_signed_in?
		@content= Content.find(params[:id])
		if current_user != @content.user
			redirect_to contents_path
		end
		else
		redirect_to contents_path
	    end

	end
	def update
		
		@content= Content.find(params[:id])
		if @content.update(content_params)
				redirect_to content_path(@content)
			else
				render :edit
			end
	
	end
	private 
	def content_params
		params.require(:content).permit(:name, :summary,:description,:picture)

	end
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

    def after_update_path_for(resource)
      user_path(resource)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def index
    @users = User.all.paginate(page: params[:page],per_page: 4) 
    
 
  end
  def show
  	@user = User.find(params[:id])
  	@contents=@user.contents.paginate(page: params[:page],per_page: 2)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/contents/edit.html.erb
<main class="mdl-layout__content">
    <div class="page-content">


<% if @content.errors.any? %>
	<div class="row">
		<div class="alert alert-danger col-md-8 col-md-offset-2">
			<h5>plz correct the following errors:</h5>
			<ul>
				<% @content.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

<%= form_for(@content, html: { multipart: true }) do |f| %>

<div class="mdl-layout mdl-js-layout mdl-color--grey-100 formcr">
	<main class="mdl-layout__content formcrw">
		<div class="mdl-card mdl-shadow--6dp">
			<div class="mdl-card__title mdl-color--primary mdl-color-text--white">
				<h2 class="mdl-card__title-text">Edit Your Content..</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<form action="#">
					<div class="mdl-textfield mdl-js-textfield">


		<%= f.label :name,class: "mdl-textfield__label", for:"name"  %>
		<%= f.text_field :name, class: "mdl-textfield__input", type:"text" ,id:"name" %>
		</div>
		<div class="mdl-textfield mdl-js-textfield">

		<%= f.label :summary , class: "mdl-textfield__label", for:"summary" %>
		<%= f.text_field :summary, class: "mdl-textfield__input", type:"text" ,id:"summary" %>
		</div>
		<div class="mdl-textfield mdl-js-textfield">
		<%= f.label :description, class: "mdl-textfield__label", for:"description" %>
		<%= f.text_area :description, rows: 7, class: "mdl-textfield__input", type:"text" ,id:"description" %>
		</div>
			
<div class="mdl-textfield mdl-js-textfield mdl-textfield--file">

		<input class="mdl-textfield__input" placeholder="Upload An Image" type="text" id="uploadFile" readonly/>

			<div class="mdl-button mdl-button--primary mdl-button--icon mdl-button--file ">
      			<i class="material-icons">add_a_photo</i>
      				<%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png', id: "uploadBtn" %>

			</div>
</div>




		<div class="mdl-card__actions mdl-card--border">

		<%= f.submit 'Edit Post', class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
		</div>
		</div>
	</main>
</div>
				<% end %>
				</div>
		</main>

<script type="text/javascript">
		document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("uploadFile").value = this.files[0].name;
};



		$('#content_picture').blind('change', function(){
			size_in_megabytes = this.files[0].size/1024/1024;
			if(size_in_megabytes > 5){
				alert('max file size is 5mb');
			}
		});
		</script>

app/views/contents/index.html.erb
<main class="mdl-layout__content">
    <div class="page-content"><!-- Your content goes here -->
  
<h1 class="textcenter"> <b>All Contents</b></h1>

<%= will_paginate %>

<% @contents.each do |content| %>
<div class="mdl-color--grey-100">
<br>
<br>
<div class="card">

  <%=  image_tag content.user.profilepic.url(:dp),class: "dpimg" if content.user.profilepic?   %>
  <div class="intro">
   <%= link_to content.user.username , user_path(content.user), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>

  </div>
  <%=  image_tag content.picture.url(:thumbnail),class: "cnimg" if content.picture?   %>
   
  <div class="container1">
  <!-- Primary-colored flat button -->
    <% if user_signed_in? %>


    <%= link_to content.name, content_path(content), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
    
    <% else %>
    
<%= link_to content.name,new_user_session_path, class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>

<% end %>
<div class="likeme" >
    <%= link_to like_content_path(content, like: true), method: :post do %>

                        <i class="material-icons" style="font-size:30px;color:#AA030B;">favorite</i>
                      
                        <% end %>
                        &nbsp&nbsp
                       <span class="mdl-badge"  data-badge="<%= content.totallike %>" >Total Likes</span>
                       </div>
    <p>Summary: <%= content.summary %></p> 
    <p>
      <span class='quite'><small>Created at: <%= time_ago_in_words(content.created_at) %> ago,</small></span>
      <span class='quite'><small>Updated at: <%= time_ago_in_words(content.updated_at) %> ago</small></span>
    </p>
  </div>

</div>

<br>
<br>




</div>





<% end %>

<%= will_paginate %>
</div>
</main>

app/views/contents/new.html.erb
<main class="mdl-layout__content">
    <div class="page-content">


<% if @content.errors.any? %>
	<div class="row">
		<div class="alert alert-danger col-md-8 col-md-offset-2">
			<h5>plz correct the following errors:</h5>
			<ul>
				<% @content.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

<%= form_for(@content, html: { multipart: true }) do |f| %>

<div class="mdl-layout mdl-js-layout mdl-color--grey-100 formcr">
	<main class="mdl-layout__content formcrw">
		<div class="mdl-card mdl-shadow--6dp">
			<div class="mdl-card__title mdl-color--primary mdl-color-text--white">
				<h2 class="mdl-card__title-text">Create Something..</h2>
			</div>
			<div class="mdl-card__supporting-text">
				<form action="#">
					<div class="mdl-textfield mdl-js-textfield">


		<%= f.label :name,class: "mdl-textfield__label", for:"name"  %>
		<%= f.text_field :name, class: "mdl-textfield__input", type:"text" ,id:"name" %>
		</div>
		<div class="mdl-textfield mdl-js-textfield">

		<%= f.label :summary , class: "mdl-textfield__label", for:"summary" %>
		<%= f.text_field :summary, class: "mdl-textfield__input", type:"text" ,id:"summary" %>
		</div>
		<div class="mdl-textfield mdl-js-textfield">
		<%= f.label :description, class: "mdl-textfield__label", for:"description" %>
		<%= f.text_area :description, rows: 7, class: "mdl-textfield__input", type:"text" ,id:"description" %>
		</div>
			
<div class="mdl-textfield mdl-js-textfield mdl-textfield--file">

		<input class="mdl-textfield__input" placeholder="Upload An Image" type="text" id="uploadFile" readonly/>

			<div class="mdl-button mdl-button--primary mdl-button--icon mdl-button--file ">
      			<i class="material-icons">add_a_photo</i>
      				<%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png', id: "uploadBtn" %>

			</div>
</div>




		<div class="mdl-card__actions mdl-card--border">

		<%= f.submit 'create Post', class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
		</div>
		</div>
	</main>
</div>
				<% end %>
				</div>
		</main>

<script type="text/javascript">
		document.getElementById("uploadBtn").onchange = function () {
    document.getElementById("uploadFile").value = this.files[0].name;
};



		$('#content_picture').blind('change', function(){
			size_in_megabytes = this.files[0].size/1024/1024;
			if(size_in_megabytes > 5){
				alert('max file size is 5mb');
			}
		});
		</script>

app/views/contents/show.html.erb
   <main class="mdl-layout__content">
    	<div class="page-content">
    		<div class="mdl-color--grey-100">
				
					<h1 class= "textcenter"><%= @content.name %></h1>
				


			<div class="mdl-grid">
			  		<div class="mdl-cell mdl-cell--6-col">
			  	
			      		<div class="cardshow">
			 				
			 					<%= image_tag @content.picture.url(:display),class: "cnimg",:alt => "Sample Image" if @content.picture? %>

					         		<div class="container1">
					         		
					         		<%= link_to like_content_path(@content, like: true), method: :post do %>

					          		<i class="material-icons" style="font-size:50px;color:#AA030B;">favorite</i>
					          	
					          		<% end %>
					          		&nbsp&nbsp
					          		<span class="mdl-badge"  data-badge="<%= @content.totallike %>" >Total Likes</span>
					         		<hr/>
					          		<h3> <%= @content.summary %></h3>
					          		
					           		<p>
									<strong>Stepes:</strong>
									<%= simple_format(@content.description) %>
						      		</p>
						      		<% if user_signed_in? and @content.user == current_user %>
						      		

    								<%= link_to "Edit This", edit_content_path(@content), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
    								
    								<% end %>
					  				</div>
						</div>


			 			 
			 		</div>
			  		<div class="mdl-cell mdl-cell--2-col">

			  		</div>

			  		<div class="mdl-cell mdl-cell--4-col">
			  			<div class="cardshow">
			  			<%= image_tag @content.user.profilepic.url(:thumbnail),:alt => "user" if @content.user.profilepic? %>
			  			<%= link_to "View Profile", user_path(@content.user), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
							 <div class="container">
			    				<h3 class="textcenter">Brought to you by: <%= @content.user.username %></h3>
			    
			  				 </div>
						</div>
					</div>

			</div>
</div>
		</div>
	</main>

app/views/contents/sortlike.html.erb
<main class="mdl-layout__content">
    <div class="page-content"><!-- Your content goes here -->
  
<h1 class="textcenter"> <b>All Contents</b></h1>

<%= will_paginate %>
<% @contents.each do |content| %>
<div class="mdl-color--grey-100">
<br>
<br>
<div class="card">
<%=  image_tag content.user.profilepic.url(:dp),class: "dpimg" if content.user.profilepic?   %>
  <div class="intro">
   <%= link_to content.user.username , user_path(content.user), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>

  </div>
  <%=  image_tag content.picture.url(:thumbnail),class: "cnimg" if content.picture?   %>
  
  <div class="container">
  <!-- Primary-colored flat button -->


    <%= link_to content.name, content_path(content), class: "mdl-button mdl-js-button mdl-button--primary" %>
    
<div class="likeme" >
    <%= link_to like_content_path(content, like: true, :anchor => "content"), method: :post do %>

                        <i class="material-icons" style="font-size:30px;color:#AA030B;">favorite</i>
                      
                        <% end %>
                        &nbsp&nbsp
                       <span class="mdl-badge"  data-badge="<%= content.totallike %>" >Total Likes</span>
                       </div>
    <p>Summary: <%= content.summary %></p> 
    <p>
      <span class='quite'><small>Created at: <%= time_ago_in_words(content.created_at) %> ago,</small></span>
      <span class='quite'><small>Updated at: <%= time_ago_in_words(content.updated_at) %> ago</small></span>
    </p>
  </div>

</div>

<br>
<br>




</div>





<% end %>
<%= will_paginate %>
</div>
</main>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
		  			<header class="mdl-layout__header">
		    				<div class="mdl-layout__header-row">
		      <!-- Title -->
		     					 <span class="mdl-layout-title"><h2 class= "logo">HomeMade</h2></span>
		     					 <!-- Left aligned menu below button -->
		     					 	
 <!-- Add spacer, to align navigation to the right -->
		      					 <div class="mdl-layout-spacer"></div>
		      <!-- Navigation. We hide it in small screens. -->
		      					 <nav class="mdl-navigation mdl-layout--large-screen-only">
		       						 <%= link_to "contents", contents_path, class: "mdl-navigation__link" %>
		       						<% if user_signed_in? %>
		        					 <%= link_to "Create", new_content_path, class: "mdl-navigation__link" %>
		        					
		        					<%= link_to "By Likes", sortlike_path, class: "mdl-navigation__link" %>
		        					<%= link_to "Users", users_path, class: "mdl-navigation__link" %>
		        					<div class="mdl-navigation__link">
		        					
		        					<button id="demo-menu-lower-left"
       								 class="mdl-button mdl-js-button mdl-button--icon">
  									<i class="material-icons">arrow_drop_down_circle</i>
									</button>
									<%= current_user.username %>
										<ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
										    for="demo-menu-lower-left">
							 <%= link_to "Your profile",user_path(current_user),class: "mdl-menu__item links" %>
										  <%= link_to "Edit Your profile",edit_user_registration_path(current_user),class: "mdl-menu__item mdl-menu__item--full-bleed-divider links" %>
										 
										  <%= link_to "Log Out",destroy_user_session_path,class: "mdl-menu__item links" %>
										</ul>
										</div>
		        					 <% else %>

		        					 <%= link_to "Log In", new_user_session_path, class: "mdl-navigation__link" %>
		        					 <% end %>
		      					 </nav>
		   				    </div>
		  			</header>
		  			
		  	<div class="mdl-layout__drawer">
		    		<span class="mdl-layout-title"><h3 class= "logo">HomeMade</h3></span>
		    		<% if user_signed_in? %>
		    		<hr />

                           &nbsp&nbsp&nbspWelcome <%= current_user.username %>
                           <nav class="mdl-navigation">
                           <%= link_to "your profile", user_path(current_user), class: "mdl-navigation__link" %>
		      				<%= link_to "Edit Profile", edit_user_registration_path(current_user), class: "mdl-navigation__link" %>
		        					<%= link_to "Log Out", destroy_user_session_path, class: "mdl-navigation__link" %>


                           </nav>
                           <hr />
                           <% end %>
		    			<nav class="mdl-navigation">
							<%= link_to "contents", contents_path, class: "mdl-navigation__link" %>
							<% if user_signed_in? %>
		        			<%= link_to "create", new_content_path, class: "mdl-navigation__link" %>
		      				<%= link_to "By Likes", sortlike_path, class: "mdl-navigation__link" %>
		        					<%= link_to "Users", users_path, class: "mdl-navigation__link" %>

		      				
		      				<% end %>
		    			</nav>
		  	</div>
		  	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homemade</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
   <!--Google Fonts-->
<%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Allura', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Barrio', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag "https://code.getmdl.io/1.3.0/material.teal-green.min.css" %>
 <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
 <% if current_page?(root_path) %>
 <%= javascript_include_tag "main_code" %>
  <%= stylesheet_link_tag    'main_code', media: 'all' %>
 <% end %>
   
  </head>
   <body>

<% unless controller.controller_name == "pages" && controller.action_name == "home" %>


 <%= render 'layouts/navigation' %>
 <% end %>

   
  <%= yield %>


</div>

</body>

</html>

app/views/users/index.html.erb
<main class="mdl-layout__content">
    <div class="page-content"><!-- Your content goes here -->
  
<h1 class="textcenter"> <b>All Users</b></h1>
<div class="mdl-color--grey-100">
<%= will_paginate %>

<div class="mdl-grid">

			  		<div class="mdl-cell mdl-cell--4-col">
			  		</div>


<br/ >

<div class="mdl-cell mdl-cell--3-col">
  <% @users.each do |user| %>


<div class="demo-card-square mdl-card mdl-shadow--2dp ">

<%=  image_tag user.profilepic.url(:thumbnail),class: "cnimg" if user.profilepic?  %>
  <div class="mdl-card__title mdl-card--expand">
    <h2 class="mdl-card__title-text"></h2>
  </div>
  <h3 class="textcenteruser"><b>&nbsp&nbsp&nbsp<%= user.username %></b></h3>
  
  <div class="mdl-card__actions mdl-card--border">
    
      <%= link_to "View Profile", user_path(user), class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
    
  </div>
</div>
<br/ >
    
    
  <% end %>
  </div>
  <div class="mdl-cell mdl-cell-5-col">
  </div>
  </div>
  
 </div>
</div>
</main>

app/views/users/show.html.erb
<main class="mdl-layout__content">
    <div class="page-content"><!-- Your content goes here -->
  
<h1 class="textcenter"> <b>Hey <%= @user.username %></b></h1>
<div class="mdl-color--grey-100">
<%= will_paginate @contents %>


<br />


			<div class="mdl-grid">

			  		<div class="mdl-cell mdl-cell--3-col fix">

<div class="cardshowus">

<%=  image_tag @user.profilepic.url(:display),class: "cnimg" if @user.profilepic?   %>
  
  </div>
  <h3 class="textcenter"><%= @user.email %></h3>
  <% if user_signed_in? and @user == current_user %>
  

    								<%= link_to "Edit Profile",  edit_user_registration_path, class: "mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" %>
    								
    								<% end %>
  </div>
<br />
<div class="mdl-cell mdl-cell--2-col">
</div>
<div class="mdl-cell mdl-cell--6-col">
<% @contents.each do |content| %>

<div class="cardshowus">
			 				
			 					<%= image_tag content.picture.url(:display),class: "cnimg" if content.picture? %>

					         		<div class="container1">
					         		
					         		<%= link_to like_content_path(content, like: true), method: :post do %>

					          		<i class="material-icons" style="font-size:50px;color:#AA030B;">favorite</i>
					          	
					          		<% end %>
					          		&nbsp&nbsp
					          		<span class="mdl-badge"  data-badge="<%= content.totallike %>" >Total Likes</span>
					         		<hr/>
					          		<h2> <%= content.summary %></h2>
					          		
					           		<p>
									<strong>Stepes:</strong>
									<%= simple_format(content.description) %>
						      		</p>
						      		<% if user_signed_in? and @user == current_user %>

    								<%= link_to "Edit This", edit_content_path(content), class: "mdl-button mdl-js-button mdl-button--primary" %>
    								<% end %>
					  				</div>
						</div>
						<br />
						<br />
<% end %>
</div>

  </div>
  <%= will_paginate @contents %>
  </div>
  </main>